### ISSUE TITLE
[FEATURE] keyfile authentication?

### ISSUE THREAD

**Issue by m-p-3** [RikyIsola/Android-SFTP-Documents-Provider#4]
**Is your feature request related to a problem? Please describe.**
I'm securing all my SSH accounts with keyfile authentication only (ed25519)

**Describe the solution you'd like**
Would it be possible to add the option to authenticate using this instead of a password?

Thanks!

**Comment by RikyIsola** [comment]
Thank you for the idea
At the moment I am rewriting the app with Kotlin and I will add this functionality to it
You can check the progress here https://github.com/RikyIsola/FileManagerUtils

**Comment by m-p-3** [comment]
Thanks, you're awesome :D
