### ISSUE TITLE
[BUG] v3.0 identifies as v1.0

### ISSUE THREAD

**Issue by IzzySoft** [RikyIsola/Android-SFTP-Documents-Provider#5]
Looks like you forgot to adjust `versionName` and `versionCode`: the APK attached to v3.0 identifies as

    package: name='com.island.androidsftpdocumentsprovider' versionCode='1' versionName='1.0' compileSdkVersion='29' compileSdkVersionCodename='10'

Expected were, according to your release history, something like `versionCode='3' versionName='3.0'`

* `versionCode`: what Android uses internally to tell versions apart and to decide if something is supposed to be an update to notify the user about (higher number)
* `versionName`: what is shown to the user (so if a user files an issue, how is (s)he supposed to know what version is installed on the device)

So before creating the next version, it's highly recommendable to fix that :wink:

**Comment by RikyIsola** [comment]
Thank you for reporting that
But I am not maintaining this project anymore because I've created a new better app with more functionalities
https://github.com/RikyIsola/FileManagerUtils

I am developing a tool to avoid errors like that in my new projects:
https://github.com/RikyIsola/AutoPublisher

**Comment by IzzySoft** [comment]
Yeah, I discovered that minutes after filing my report – but as this repo here wasn't archived, I decided to leave the issue open. As for the successor, I even promote it now: interested users can install it [via my repo](https://apt.izzysoft.de/fdroid/index/apk/com.island.filemanagerutils) using the F-Droid client, so be welcome to add [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from the Readme :smiley:
